name: Windows build

on:
#  schedule:
#    - cron: '*/30 * * * *'
  workflow_dispatch:
  
jobs:
  WindowsBuild:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Get latest commit
      run: |
        git clone https://${{ secrets.ASE_GITHUB_TOKEN }}@github.com/${{ secrets.MY_REPO_URL }} ${{ secrets.FILENAME }} --depth=1
        cd ${{ secrets.FILENAME }}
        git log -1 --pretty=format:"%H" > ../latest_commit.txt
        cd ..
        $latest_commit = (Get-Content "latest_commit.txt" | ForEach-Object { $_.Trim() }) -join ''
        $current_hash = (Get-Content "latestHash" | ForEach-Object { $_.Trim() }) -join ''
        if ($latest_commit -eq $current_hash) {
          Write-Output "Hashes are the same"
          Add-Content -Path $env:GITHUB_ENV -Value "hashes_are_same=true"
        } else {
          Write-Output "Hashes are different"
          Add-Content -Path $env:GITHUB_ENV -Value "hashes_are_same=false"
        }
    - name: Update latestHash in current repository
      if: env.hashes_are_same == 'false'
      run: |
        cd $GITHUB_WORKSPACE
        (Get-Content "latest_commit.txt" | ForEach-Object { $_.Trim() }) -join '' | Out-File -FilePath "latestHash" -Force
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add latestHash
        $current_date = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        git commit -m "Update latestHash at $current_date"
        git remote set-url origin https://${{ secrets.ASE_GITHUB_TOKEN }}@github.com/ArtCrush/_blank
        git push